// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelCapture(): $CancellablePromise<void> {
    return $Call.ByID(4264228573);
}

export function CloseCaptureWindow(): $CancellablePromise<void> {
    return $Call.ByID(1676460121);
}

export function CopyToClipboard(req: $models.ExportRequest): $CancellablePromise<void> {
    return $Call.ByID(1691332723, req);
}

export function GetCaptureState(): $CancellablePromise<$models.CaptureSession | null> {
    return $Call.ByID(3188152366).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPreferences(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1830607729).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Init(): $CancellablePromise<void> {
    return $Call.ByID(3371081681);
}

export function OverlayLog(message: string): $CancellablePromise<void> {
    return $Call.ByID(2794503145, message);
}

export function PrewarmOverlay(): $CancellablePromise<void> {
    return $Call.ByID(2734737507);
}

export function SaveToFile(path: string, req: $models.ExportRequest): $CancellablePromise<void> {
    return $Call.ByID(2853757337, path, req);
}

export function SaveWithDialog(req: $models.ExportRequest): $CancellablePromise<string> {
    return $Call.ByID(1323388366, req);
}

export function SelectDefaultSaveFolder(): $CancellablePromise<string> {
    return $Call.ByID(770821093);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(675474388, app);
}

export function SetLaunchAtLogin(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3550358152, enabled);
}

export function ShowError(title: string, err: any): $CancellablePromise<void> {
    return $Call.ByID(1966328540, title, err);
}

export function TriggerCapture(): $CancellablePromise<void> {
    return $Call.ByID(2025580405);
}

// Private type creation functions
const $$createType0 = $models.CaptureSession.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AppConfig.createFrom;
