// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Annotation {
    "type": string;
    "color": string;
    "x1": number;
    "y1": number;
    "x2": number;
    "y2": number;
    "text": string;
    "fontSize": number;

    /** Creates a new Annotation instance. */
    constructor($$source: Partial<Annotation> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("x1" in $$source)) {
            this["x1"] = 0;
        }
        if (!("y1" in $$source)) {
            this["y1"] = 0;
        }
        if (!("x2" in $$source)) {
            this["x2"] = 0;
        }
        if (!("y2" in $$source)) {
            this["y2"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Annotation instance from a string or object.
     */
    static createFrom($$source: any = {}): Annotation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Annotation($$parsedSource as Partial<Annotation>);
    }
}

export class AppConfig {
    "defaultSaveDir": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("defaultSaveDir" in $$source)) {
            this["defaultSaveDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class CaptureScreen {
    "name": string;
    "width": number;
    "height": number;
    "pixelWidth": number;
    "pixelHeight": number;
    "scaleFactor": number;

    /** Creates a new CaptureScreen instance. */
    constructor($$source: Partial<CaptureScreen> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("pixelWidth" in $$source)) {
            this["pixelWidth"] = 0;
        }
        if (!("pixelHeight" in $$source)) {
            this["pixelHeight"] = 0;
        }
        if (!("scaleFactor" in $$source)) {
            this["scaleFactor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureScreen instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureScreen {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureScreen($$parsedSource as Partial<CaptureScreen>);
    }
}

export class CaptureSession {
    "imageBase64": string;
    "screen": CaptureScreen;
    "selection": SelectionBounds;

    /** Creates a new CaptureSession instance. */
    constructor($$source: Partial<CaptureSession> = {}) {
        if (!("imageBase64" in $$source)) {
            this["imageBase64"] = "";
        }
        if (!("screen" in $$source)) {
            this["screen"] = (new CaptureScreen());
        }
        if (!("selection" in $$source)) {
            this["selection"] = (new SelectionBounds());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureSession instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureSession {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("screen" in $$parsedSource) {
            $$parsedSource["screen"] = $$createField1_0($$parsedSource["screen"]);
        }
        if ("selection" in $$parsedSource) {
            $$parsedSource["selection"] = $$createField2_0($$parsedSource["selection"]);
        }
        return new CaptureSession($$parsedSource as Partial<CaptureSession>);
    }
}

export class ExportRequest {
    "selection": SelectionBounds;
    "annotations": Annotation[];
    "viewportWidth": number;
    "viewportHeight": number;

    /** Creates a new ExportRequest instance. */
    constructor($$source: Partial<ExportRequest> = {}) {
        if (!("selection" in $$source)) {
            this["selection"] = (new SelectionBounds());
        }
        if (!("annotations" in $$source)) {
            this["annotations"] = [];
        }
        if (!("viewportWidth" in $$source)) {
            this["viewportWidth"] = 0;
        }
        if (!("viewportHeight" in $$source)) {
            this["viewportHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRequest {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selection" in $$parsedSource) {
            $$parsedSource["selection"] = $$createField0_0($$parsedSource["selection"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField1_0($$parsedSource["annotations"]);
        }
        return new ExportRequest($$parsedSource as Partial<ExportRequest>);
    }
}

export class SelectionBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new SelectionBounds instance. */
    constructor($$source: Partial<SelectionBounds> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectionBounds instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectionBounds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectionBounds($$parsedSource as Partial<SelectionBounds>);
    }
}

// Private type creation functions
const $$createType0 = CaptureScreen.createFrom;
const $$createType1 = SelectionBounds.createFrom;
const $$createType2 = Annotation.createFrom;
const $$createType3 = $Create.Array($$createType2);
